/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stee_riskmgr.proto */

#ifndef PROTOBUF_C_stee_5friskmgr_2eproto__INCLUDED
#define PROTOBUF_C_stee_5friskmgr_2eproto__INCLUDED

#include <protobuf-c/dx_protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

void pb_stee_riskmgr_com__dingxiang__mobile__init();

typedef struct _Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest;
typedef struct _Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse;
typedef struct _Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest;
typedef struct _Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem;
typedef struct _Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse;


/* --- enums --- */

typedef enum _Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse__STEEConfigAction {
  /*
   *立刻上报
   */
  COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_RESPONSE__STEECONFIG_ACTION__ATONCE = 0,
  /*
   *放弃上报
   */
  COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_RESPONSE__STEECONFIG_ACTION__GIVEUP = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_RESPONSE__STEECONFIG_ACTION)
} Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse__STEEConfigAction;

/* --- messages --- */

/*
 * 数据采集配置
 */
struct  _Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest
{
  ProtobufCMessage base;
  /*
   *标签，用于标识本次数据上报的触发场景，如"first_run"(app首次启动)等等
   */
  char *tag;
};
#define COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor) \
    , NULL }


struct  _Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse
{
  ProtobufCMessage base;
  Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse__STEEConfigAction action;
  /*
   *黑名单过滤
   */
  size_t n_filters;
  char **filters;
};
#define COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor) \
    , COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_RESPONSE__STEECONFIG_ACTION__ATONCE, 0,NULL }


/*
 * 数据采集上传
 */
struct  _Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem
{
  ProtobufCMessage base;
  char *name;
  char *value;
};
#define COM__DINGXIANG__MOBILE__STEERISK_MGR_REPORT_DATA_REQUEST__STEEINFO_ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor) \
    , NULL, NULL }


struct  _Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest
{
  ProtobufCMessage base;
  /*
   *键值对方式保证数据
   */
  size_t n_infos;
  Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem **infos;
  /*
   *客户自定义的字段，key默认为usr_data_1, usr_data_2，如此类推
   */
  size_t n_usr_infos;
  Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem **usr_infos;
};
#define COM__DINGXIANG__MOBILE__STEERISK_MGR_REPORT_DATA_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse
{
  ProtobufCMessage base;
  /*
   *风控系统返回的token
   */
  char *constid;
};
#define COM__DINGXIANG__MOBILE__STEERISK_MGR_REPORT_DATA_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor) \
    , NULL }


/* Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest methods */
void   com__dingxiang__mobile__steerisk_mgr_get_report_config_request__init
                     (Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest         *message);
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_request__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest   *message);
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_request__pack
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest   *message,
                      uint8_t             *out);
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_request__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest   *message,
                      ProtobufCBuffer     *buffer);
Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest *
       com__dingxiang__mobile__steerisk_mgr_get_report_config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__dingxiang__mobile__steerisk_mgr_get_report_config_request__free_unpacked
                     (Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest *message,
                      ProtobufCAllocator *allocator);
/* Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse methods */
void   com__dingxiang__mobile__steerisk_mgr_get_report_config_response__init
                     (Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse         *message);
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_response__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse   *message);
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_response__pack
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse   *message,
                      uint8_t             *out);
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_response__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse   *message,
                      ProtobufCBuffer     *buffer);
Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse *
       com__dingxiang__mobile__steerisk_mgr_get_report_config_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__dingxiang__mobile__steerisk_mgr_get_report_config_response__free_unpacked
                     (Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse *message,
                      ProtobufCAllocator *allocator);
/* Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem methods */
void   com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__init
                     (Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem         *message);
/* Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest methods */
void   com__dingxiang__mobile__steerisk_mgr_report_data_request__init
                     (Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest         *message);
size_t com__dingxiang__mobile__steerisk_mgr_report_data_request__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest   *message);
size_t com__dingxiang__mobile__steerisk_mgr_report_data_request__pack
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest   *message,
                      uint8_t             *out);
size_t com__dingxiang__mobile__steerisk_mgr_report_data_request__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest   *message,
                      ProtobufCBuffer     *buffer);
Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest *
       com__dingxiang__mobile__steerisk_mgr_report_data_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__dingxiang__mobile__steerisk_mgr_report_data_request__free_unpacked
                     (Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest *message,
                      ProtobufCAllocator *allocator);
/* Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse methods */
void   com__dingxiang__mobile__steerisk_mgr_report_data_response__init
                     (Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse         *message);
size_t com__dingxiang__mobile__steerisk_mgr_report_data_response__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse   *message);
size_t com__dingxiang__mobile__steerisk_mgr_report_data_response__pack
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse   *message,
                      uint8_t             *out);
size_t com__dingxiang__mobile__steerisk_mgr_report_data_response__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse   *message,
                      ProtobufCBuffer     *buffer);
Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse *
       com__dingxiang__mobile__steerisk_mgr_report_data_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__dingxiang__mobile__steerisk_mgr_report_data_response__free_unpacked
                     (Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest_Closure)
                 (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest *message,
                  void *closure_data);
typedef void (*Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse_Closure)
                 (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse *message,
                  void *closure_data);
typedef void (*Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem_Closure)
                 (const Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem *message,
                  void *closure_data);
typedef void (*Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest_Closure)
                 (const Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest *message,
                  void *closure_data);
typedef void (*Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse_Closure)
                 (const Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor;
extern ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor;
extern ProtobufCEnumDescriptor    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor;
extern ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor;
extern ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor;
extern ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_stee_5friskmgr_2eproto__INCLUDED */
