stages:
- prepare
- build
- test
- run
- check
- deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

init-env:
  stage: prepare
  variables:
    GIT_SUBMODULE_STRATEGY: ''
  tags:
    - default
  image: docker:git
  services:
    - docker:dind
  before_script:
    - apk --cache-dir=/cache update
    - apk --cache-dir=/cache add bash tree
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - chmod 755 *.sh
  script:
    - ./dx-init-env.sh
  artifacts:
    expire_in: 2 day
    paths:
      - dx-hook
      - dx-libc

by-stee:
  image: dev.dingxiang-inc.com:4567/stee/dockers/dx-ndk:r15c
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - chmod 755 *.sh
  script:
    - ./build.sh
    - ./strip.sh
  allow_failure: false
  artifacts:
    expire_in: 2 day
    paths:
      - anti

test-case:
  image: dev.dingxiang-inc.com:4567/stee/dockers/dx-ndk:r15c 
  #dev.dingxiang-inc.com:4567/bob/android-sdk:ndk-r14b-as
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - (yes | $ANDROID_HOME/tools/bin/sdkmanager --update) && (yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses)
    - chmod +x *.sh
  script:
    - ./test_case.sh
  allow_failure: false
  artifacts:
    expire_in: 1 day
    paths:
      - apks

test_phone:
  stage: run
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - gz-minitestin-ubuntu
  script:
    - python /var/opt/DXTester/caserunner.py -i test-case.json -rp test-phone.csv -ld "logout-phone"
  except:
    - develop
    - master
    - tags
  artifacts:
    expire_in: 1 day
    paths:
      - test-phone.csv
      - logout-phone/*


test_emulator:
  stage: run
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - gz-minitestin
  script:
    - python /d/DXTester/caserunner.py -i test-case.json -rp test-emulator.csv -ld "logout-emulator"
  except:
    - develop
    - master
    - tags
  artifacts:
    expire_in: 1 day
    paths:
      - test-emulator.csv
      - logout-emulator/*


check_all:
  stage: check
  # tags:
  #   - hz-a122
  script: 
    - ./ci-test.sh logout-emulator/test
    - ./ci-test.sh logout-phone/test
  except:
    - develop
    - master
    - tags
  artifacts:
    expire_in: 1 day
    

deploy-to-dockers:
  stage: deploy
  tags:
    - default
  image: docker:git
  services:
    - docker:dind
  before_script:
    - apk --cache-dir=/cache update
    - apk --cache-dir=/cache add bash
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - chmod 755 *.sh
  script:
    - gitlab_login_dockers
    - ./dx-push.sh ./anti/
  only:
    - tags
