# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Prototype' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'
  pod 'Toast-Swift'
  pod 'IQKeyboardManagerSwift'
  pod 'ZWPlaceHolder'
  pod 'YSHttpManager'
  
end
