/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stee_riskmgr.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "stee_riskmgr.pb-c.h"
void   com__dingxiang__mobile__steerisk_mgr_get_report_config_request__init
                     (Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest         *message)
{
  static const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest init_value = COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_REQUEST__INIT;
  *message = init_value;
}
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_request__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest *message)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_request__pack
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_request__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest *
       com__dingxiang__mobile__steerisk_mgr_get_report_config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest *)
     protobuf_c_message_unpack (&com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor,
                                allocator, len, data);
}
void   com__dingxiang__mobile__steerisk_mgr_get_report_config_request__free_unpacked
                     (Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   com__dingxiang__mobile__steerisk_mgr_get_report_config_response__init
                     (Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse         *message)
{
  static const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse init_value = COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_RESPONSE__INIT;
  *message = init_value;
}
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_response__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse *message)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_response__pack
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__dingxiang__mobile__steerisk_mgr_get_report_config_response__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse *
       com__dingxiang__mobile__steerisk_mgr_get_report_config_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse *)
     protobuf_c_message_unpack (&com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor,
                                allocator, len, data);
}
void   com__dingxiang__mobile__steerisk_mgr_get_report_config_response__free_unpacked
                     (Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__init
                     (Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem         *message)
{
  static const Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem init_value = COM__DINGXIANG__MOBILE__STEERISK_MGR_REPORT_DATA_REQUEST__STEEINFO_ITEM__INIT;
  *message = init_value;
}
void   com__dingxiang__mobile__steerisk_mgr_report_data_request__init
                     (Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest         *message)
{
  static const Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest init_value = COM__DINGXIANG__MOBILE__STEERISK_MGR_REPORT_DATA_REQUEST__INIT;
  *message = init_value;
}
size_t com__dingxiang__mobile__steerisk_mgr_report_data_request__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest *message)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__dingxiang__mobile__steerisk_mgr_report_data_request__pack
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__dingxiang__mobile__steerisk_mgr_report_data_request__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest *
       com__dingxiang__mobile__steerisk_mgr_report_data_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest *)
     protobuf_c_message_unpack (&com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor,
                                allocator, len, data);
}
void   com__dingxiang__mobile__steerisk_mgr_report_data_request__free_unpacked
                     (Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   com__dingxiang__mobile__steerisk_mgr_report_data_response__init
                     (Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse         *message)
{
  static const Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse init_value = COM__DINGXIANG__MOBILE__STEERISK_MGR_REPORT_DATA_RESPONSE__INIT;
  *message = init_value;
}
size_t com__dingxiang__mobile__steerisk_mgr_report_data_response__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse *message)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__dingxiang__mobile__steerisk_mgr_report_data_response__pack
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__dingxiang__mobile__steerisk_mgr_report_data_response__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse *
       com__dingxiang__mobile__steerisk_mgr_report_data_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse *)
     protobuf_c_message_unpack (&com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor,
                                allocator, len, data);
}
void   com__dingxiang__mobile__steerisk_mgr_report_data_response__free_unpacked
                     (Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_request__field_descriptors[1] =
{
  {
    "tag",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest, tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__dingxiang__mobile__steerisk_mgr_get_report_config_request__field_indices_by_name[] = {
  0,   /* field[0] = tag */
};
static const ProtobufCIntRange com__dingxiang__mobile__steerisk_mgr_get_report_config_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
//const ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor =
//{
//  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
//  "com.dingxiang.mobile.STEERiskMgrGetReportConfigRequest",
//  "STEERiskMgrGetReportConfigRequest",
//  "Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest",
//  "com.dingxiang.mobile",
//  sizeof(Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest),
//  1,
//  com__dingxiang__mobile__steerisk_mgr_get_report_config_request__field_descriptors,
//  com__dingxiang__mobile__steerisk_mgr_get_report_config_request__field_indices_by_name,
//  1,  com__dingxiang__mobile__steerisk_mgr_get_report_config_request__number_ranges,
//  (ProtobufCMessageInit) com__dingxiang__mobile__steerisk_mgr_get_report_config_request__init,
//  NULL,NULL,NULL    /* reserved[123] */
//};

ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor;
void init_com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor() {

    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.magic = PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.name = "com.dingxiang.mobile.STEERiskMgrGetReportConfigRequest";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.short_name = "STEERiskMgrGetReportConfigRequest";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.c_name = "Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.sizeof_message = sizeof(Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigRequest);
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.n_fields = 1;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.fields = com__dingxiang__mobile__steerisk_mgr_get_report_config_request__field_descriptors;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.fields_sorted_by_name = com__dingxiang__mobile__steerisk_mgr_get_report_config_request__field_indices_by_name;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.n_field_ranges = 1;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.field_ranges = com__dingxiang__mobile__steerisk_mgr_get_report_config_request__number_ranges;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.message_init = (ProtobufCMessageInit) com__dingxiang__mobile__steerisk_mgr_get_report_config_request__init;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.reserved1 = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor.reserved3 = NULL;
}

//static const ProtobufCEnumValue com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number[2] =
//{
//  { "ATONCE", "COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_RESPONSE__STEECONFIG_ACTION__ATONCE", 0 },
//  { "GIVEUP", "COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_RESPONSE__STEECONFIG_ACTION__GIVEUP", 1 },
//};
static ProtobufCEnumValue com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number[2];
void init_com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number() {
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number[0].name = "ATONCE";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number[0].c_name = "COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_RESPONSE__STEECONFIG_ACTION__ATONCE";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number[0].value = 0;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number[1].name = "GIVEUP";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number[1].c_name = "COM__DINGXIANG__MOBILE__STEERISK_MGR_GET_REPORT_CONFIG_RESPONSE__STEECONFIG_ACTION__GIVEUP";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number[1].value = 1;
}


static const ProtobufCIntRange com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__value_ranges[] = {
{0, 0},{0, 2}
};
//static const ProtobufCEnumValueIndex com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_name[2] =
//{
//  { "ATONCE", 0 },
//  { "GIVEUP", 1 },
//};
static ProtobufCEnumValueIndex com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_name[2];
void init_com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_name() {
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_name[0].name = "ATONCE";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_name[0].index = 0;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_name[1].name = "GIVEUP";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_name[1].index = 1;
}


//const ProtobufCEnumDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor =
//{
//  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
//  "com.dingxiang.mobile.STEERiskMgrGetReportConfigResponse.STEEConfigAction",
//  "STEEConfigAction",
//  "Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse__STEEConfigAction",
//  "com.dingxiang.mobile",
//  2,
//  com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number,
//  2,
//  com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_name,
//  1,
//  com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__value_ranges,
//  NULL,NULL,NULL,NULL   /* reserved[1234] */
//};
ProtobufCEnumDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor;
void init_com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor() {
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.magic  = PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.name  = "com.dingxiang.mobile.STEERiskMgrGetReportConfigResponse.STEEConfigAction";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.short_name  = "STEEConfigAction";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.c_name  = "Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse__STEEConfigAction";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.n_values  = 2;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.values  = com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.n_value_names = 2;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.values_by_name = com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_name;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.n_value_ranges = 1;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.value_ranges = com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__value_ranges;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.reserved1  = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.reserved2  = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.reserved3  = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor.reserved4  = NULL;
}


//static const ProtobufCFieldDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[2] =
//{
//  {
//    "action",
//    1,
//    PROTOBUF_C_LABEL_REQUIRED,
//    PROTOBUF_C_TYPE_ENUM,
//    0,   /* quantifier_offset */
//    offsetof(Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse, action),
//    &com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor,
//    NULL,
//    0,             /* flags */
//    0,NULL,NULL    /* reserved1,reserved2, etc */
//  },
//  {
//    "filters",
//    2,
//    PROTOBUF_C_LABEL_REPEATED,
//    PROTOBUF_C_TYPE_STRING,
//    offsetof(Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse, n_filters),
//    offsetof(Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse, filters),
//    NULL,
//    NULL,
//    0,             /* flags */
//    0,NULL,NULL    /* reserved1,reserved2, etc */
//  },
//};

static ProtobufCFieldDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[2];
void init_com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors() {

    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].name = "action";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].id = 1;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].label = PROTOBUF_C_LABEL_REQUIRED;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].type = PROTOBUF_C_TYPE_ENUM;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].quantifier_offset = 0;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].offset = offsetof(
            Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse, action);
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].descriptor = &com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].default_value = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].flags = 0;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].reserved_flags = 0;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[0].reserved3 = NULL;

    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].name = "filters";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].id = 2;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].label = PROTOBUF_C_LABEL_REPEATED;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].type = PROTOBUF_C_TYPE_STRING;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].quantifier_offset = offsetof(Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse, n_filters);
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].offset = offsetof(
            Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse, filters);
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].descriptor = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].default_value = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].flags = 0;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].reserved_flags = 0;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors[1].reserved3 = NULL;
}



static const unsigned com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_indices_by_name[] = {
  0,   /* field[0] = action */
  1,   /* field[1] = filters */
};
static const ProtobufCIntRange com__dingxiang__mobile__steerisk_mgr_get_report_config_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
//const ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor =
//{
//  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
//  "com.dingxiang.mobile.STEERiskMgrGetReportConfigResponse",
//  "STEERiskMgrGetReportConfigResponse",
//  "Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse",
//  "com.dingxiang.mobile",
//  sizeof(Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse),
//  2,
//  com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors,
//  com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_indices_by_name,
//  1,  com__dingxiang__mobile__steerisk_mgr_get_report_config_response__number_ranges,
//  (ProtobufCMessageInit) com__dingxiang__mobile__steerisk_mgr_get_report_config_response__init,
//  NULL,NULL,NULL    /* reserved[123] */
//};

ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor;
void init_com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor() {

    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.magic = PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.name = "com.dingxiang.mobile.STEERiskMgrGetReportConfigResponse";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.short_name = "STEERiskMgrGetReportConfigResponse";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.c_name = "Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.sizeof_message = sizeof(Com__Dingxiang__Mobile__STEERiskMgrGetReportConfigResponse);
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.n_fields = 2;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.fields = com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.fields_sorted_by_name = com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_indices_by_name;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.n_field_ranges = 1;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.field_ranges = com__dingxiang__mobile__steerisk_mgr_get_report_config_response__number_ranges;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.message_init = (ProtobufCMessageInit) com__dingxiang__mobile__steerisk_mgr_get_report_config_response__init;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.reserved1 = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor.reserved3 = NULL;
}


//static const ProtobufCFieldDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[2] =
//{
//  {
//    "name",
//    1,
//    PROTOBUF_C_LABEL_REQUIRED,
//    PROTOBUF_C_TYPE_STRING,
//    0,   /* quantifier_offset */
//    offsetof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem, name),
//    NULL,
//    NULL,
//    0,             /* flags */
//    0,NULL,NULL    /* reserved1,reserved2, etc */
//  },
//  {
//    "value",
//    2,
//    PROTOBUF_C_LABEL_REQUIRED,
//    PROTOBUF_C_TYPE_STRING,
//    0,   /* quantifier_offset */
//    offsetof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem, value),
//    NULL,
//    NULL,
//    0,             /* flags */
//    0,NULL,NULL    /* reserved1,reserved2, etc */
//  },
//};

static ProtobufCFieldDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[2];
void init_com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors() {

    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].name = "name";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].id = 1;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].label = PROTOBUF_C_LABEL_REQUIRED;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].type = PROTOBUF_C_TYPE_STRING;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].quantifier_offset = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].offset = offsetof(
            Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem, name);
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].descriptor = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].default_value = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].flags = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].reserved_flags = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[0].reserved3 = NULL;

    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].name = "value";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].id = 2;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].label = PROTOBUF_C_LABEL_REQUIRED;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].type = PROTOBUF_C_TYPE_STRING;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].quantifier_offset = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].offset = offsetof(
            Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem, value);
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].descriptor = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].default_value = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].flags = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].reserved_flags = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors[1].reserved3 = NULL;
}



static const unsigned com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
//const ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor =
//{
//  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
//  "com.dingxiang.mobile.STEERiskMgrReportDataRequest.STEEInfoItem",
//  "STEEInfoItem",
//  "Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem",
//  "com.dingxiang.mobile",
//  sizeof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem),
//  2,
//  com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors,
//  com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_indices_by_name,
//  1,  com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__number_ranges,
//  (ProtobufCMessageInit) com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__init,
//  NULL,NULL,NULL    /* reserved[123] */
//};

ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor;
void init_com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor() {

    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.magic = PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.name = "com.dingxiang.mobile.STEERiskMgrReportDataRequest.STEEInfoItem";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.short_name = "STEEInfoItem";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.c_name = "Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.sizeof_message = sizeof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest__STEEInfoItem);
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.n_fields = 2;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.fields = com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.fields_sorted_by_name = com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_indices_by_name;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.n_field_ranges = 1;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.field_ranges = com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__number_ranges;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.message_init = (ProtobufCMessageInit) com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__init;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.reserved1 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor.reserved3 = NULL;
}


//static const ProtobufCFieldDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[2] =
//{
//  {
//    "infos",
//    1,
//    PROTOBUF_C_LABEL_REPEATED,
//    PROTOBUF_C_TYPE_MESSAGE,
//    offsetof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest, n_infos),
//    offsetof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest, infos),
//    &com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor,
//    NULL,
//    0,             /* flags */
//    0,NULL,NULL    /* reserved1,reserved2, etc */
//  },
//  {
//    "usr_infos",
//    2,
//    PROTOBUF_C_LABEL_REPEATED,
//    PROTOBUF_C_TYPE_MESSAGE,
//    offsetof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest, n_usr_infos),
//    offsetof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest, usr_infos),
//    &com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor,
//    NULL,
//    0,             /* flags */
//    0,NULL,NULL    /* reserved1,reserved2, etc */
//  },
//};

static ProtobufCFieldDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[2];
void init_com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors() {

    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].name = "infos";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].id = 1;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].label = PROTOBUF_C_LABEL_REPEATED;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].type = PROTOBUF_C_TYPE_MESSAGE;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].quantifier_offset = offsetof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest, n_infos);
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].offset = offsetof(
            Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest, infos);
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].descriptor = &com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].default_value = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].flags = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].reserved_flags = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[0].reserved3 = NULL;

    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].name = "usr_infos";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].id = 2;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].label = PROTOBUF_C_LABEL_REPEATED;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].type = PROTOBUF_C_TYPE_MESSAGE;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].quantifier_offset = offsetof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest, n_usr_infos);
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].offset = offsetof(
            Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest, usr_infos);
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].descriptor = &com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].default_value = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].flags = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].reserved_flags = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors[1].reserved3 = NULL;
}

static const unsigned com__dingxiang__mobile__steerisk_mgr_report_data_request__field_indices_by_name[] = {
  0,   /* field[0] = infos */
  1,   /* field[1] = usr_infos */
};
static const ProtobufCIntRange com__dingxiang__mobile__steerisk_mgr_report_data_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
//const ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor =
//{
//  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
//  "com.dingxiang.mobile.STEERiskMgrReportDataRequest",
//  "STEERiskMgrReportDataRequest",
//  "Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest",
//  "com.dingxiang.mobile",
//  sizeof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest),
//  2,
//  com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors,
//  com__dingxiang__mobile__steerisk_mgr_report_data_request__field_indices_by_name,
//  1,  com__dingxiang__mobile__steerisk_mgr_report_data_request__number_ranges,
//  (ProtobufCMessageInit) com__dingxiang__mobile__steerisk_mgr_report_data_request__init,
//  NULL,NULL,NULL    /* reserved[123] */
//};

ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor;
void init_com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor() {

    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.magic = PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.name = "com.dingxiang.mobile.STEERiskMgrReportDataRequest";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.short_name = "STEERiskMgrReportDataRequest";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.c_name = "Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.sizeof_message = sizeof(Com__Dingxiang__Mobile__STEERiskMgrReportDataRequest);
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.n_fields = 2;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.fields = com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.fields_sorted_by_name = com__dingxiang__mobile__steerisk_mgr_report_data_request__field_indices_by_name;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.n_field_ranges = 1;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.field_ranges = com__dingxiang__mobile__steerisk_mgr_report_data_request__number_ranges;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.message_init = (ProtobufCMessageInit) com__dingxiang__mobile__steerisk_mgr_report_data_request__init;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.reserved1 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor.reserved3 = NULL;
}

//static const ProtobufCFieldDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[1] =
//{
//  {
//    "constid",
//    1,
//    PROTOBUF_C_LABEL_REQUIRED,
//    PROTOBUF_C_TYPE_STRING,
//    0,   /* quantifier_offset */
//    offsetof(Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse, constid),
//    NULL,
//    NULL,
//    0,             /* flags */
//    0,NULL,NULL    /* reserved1,reserved2, etc */
//  },
//};


static ProtobufCFieldDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[1];
void init_com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors() {

    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].name = "constid";
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].id = 1;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].label = PROTOBUF_C_LABEL_REQUIRED;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].type = PROTOBUF_C_TYPE_STRING;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].quantifier_offset = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].offset = offsetof(
            Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse, constid);
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].descriptor = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].default_value = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].flags = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].reserved_flags = 0;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors[0].reserved3 = NULL;
}

static const unsigned com__dingxiang__mobile__steerisk_mgr_report_data_response__field_indices_by_name[] = {
  0,   /* field[0] = constid */
};
static const ProtobufCIntRange com__dingxiang__mobile__steerisk_mgr_report_data_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
//const ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor =
//{
//  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
//  "com.dingxiang.mobile.STEERiskMgrReportDataResponse",
//  "STEERiskMgrReportDataResponse",
//  "Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse",
//  "com.dingxiang.mobile",
//  sizeof(Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse),
//  1,
//  com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors,
//  com__dingxiang__mobile__steerisk_mgr_report_data_response__field_indices_by_name,
//  1,  com__dingxiang__mobile__steerisk_mgr_report_data_response__number_ranges,
//  (ProtobufCMessageInit) com__dingxiang__mobile__steerisk_mgr_report_data_response__init,
//  NULL,NULL,NULL    /* reserved[123] */
//};

ProtobufCMessageDescriptor com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor;
void init_com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor() {

    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.magic = PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.name = "com.dingxiang.mobile.STEERiskMgrReportDataResponse";
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.short_name = "STEERiskMgrReportDataResponse";
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.c_name = "Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse";
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.sizeof_message = sizeof(Com__Dingxiang__Mobile__STEERiskMgrReportDataResponse);
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.n_fields = 1;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.fields = com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.fields_sorted_by_name = com__dingxiang__mobile__steerisk_mgr_report_data_response__field_indices_by_name;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.n_field_ranges = 1;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.field_ranges = com__dingxiang__mobile__steerisk_mgr_report_data_response__number_ranges;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.message_init = (ProtobufCMessageInit) com__dingxiang__mobile__steerisk_mgr_report_data_response__init;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.reserved1 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.reserved2 = NULL;
    com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor.reserved3 = NULL;
}

void pb_stee_riskmgr_com__dingxiang__mobile__init() {

    init_com__dingxiang__mobile__steerisk_mgr_get_report_config_request__descriptor();
    init_com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_number();
    init_com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__enum_values_by_name();
    init_com__dingxiang__mobile__steerisk_mgr_get_report_config_response__steeconfig_action__descriptor();
    init_com__dingxiang__mobile__steerisk_mgr_get_report_config_response__field_descriptors();
    init_com__dingxiang__mobile__steerisk_mgr_get_report_config_response__descriptor();
    init_com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__field_descriptors();
    init_com__dingxiang__mobile__steerisk_mgr_report_data_request__steeinfo_item__descriptor();
    init_com__dingxiang__mobile__steerisk_mgr_report_data_request__field_descriptors();
    init_com__dingxiang__mobile__steerisk_mgr_report_data_request__descriptor();
    init_com__dingxiang__mobile__steerisk_mgr_report_data_response__field_descriptors();
    init_com__dingxiang__mobile__steerisk_mgr_report_data_response__descriptor();

}