/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stee_base.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "stee_base.pb-c.h"
void   com__dingxiang__mobile__steerequest_header__init
                     (Com__Dingxiang__Mobile__STEERequestHeader         *message)
{
  static const Com__Dingxiang__Mobile__STEERequestHeader init_value = COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__INIT;
  *message = init_value;
}
size_t com__dingxiang__mobile__steerequest_header__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERequestHeader *message)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerequest_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__dingxiang__mobile__steerequest_header__pack
                     (const Com__Dingxiang__Mobile__STEERequestHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerequest_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__dingxiang__mobile__steerequest_header__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERequestHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerequest_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Dingxiang__Mobile__STEERequestHeader *
       com__dingxiang__mobile__steerequest_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Dingxiang__Mobile__STEERequestHeader *)
     protobuf_c_message_unpack (&com__dingxiang__mobile__steerequest_header__descriptor,
                                allocator, len, data);
}
void   com__dingxiang__mobile__steerequest_header__free_unpacked
                     (Com__Dingxiang__Mobile__STEERequestHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__dingxiang__mobile__steerequest_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   com__dingxiang__mobile__steerequest__init
                     (Com__Dingxiang__Mobile__STEERequest         *message)
{
  static const Com__Dingxiang__Mobile__STEERequest init_value = COM__DINGXIANG__MOBILE__STEEREQUEST__INIT;
  *message = init_value;
}
size_t com__dingxiang__mobile__steerequest__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERequest *message)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerequest__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__dingxiang__mobile__steerequest__pack
                     (const Com__Dingxiang__Mobile__STEERequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerequest__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__dingxiang__mobile__steerequest__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steerequest__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Dingxiang__Mobile__STEERequest *
       com__dingxiang__mobile__steerequest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Dingxiang__Mobile__STEERequest *)
     protobuf_c_message_unpack (&com__dingxiang__mobile__steerequest__descriptor,
                                allocator, len, data);
}
void   com__dingxiang__mobile__steerequest__free_unpacked
                     (Com__Dingxiang__Mobile__STEERequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__dingxiang__mobile__steerequest__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   com__dingxiang__mobile__steeresponse__init
                     (Com__Dingxiang__Mobile__STEEResponse         *message)
{
  static const Com__Dingxiang__Mobile__STEEResponse init_value = COM__DINGXIANG__MOBILE__STEERESPONSE__INIT;
  *message = init_value;
}
size_t com__dingxiang__mobile__steeresponse__get_packed_size
                     (const Com__Dingxiang__Mobile__STEEResponse *message)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steeresponse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__dingxiang__mobile__steeresponse__pack
                     (const Com__Dingxiang__Mobile__STEEResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steeresponse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__dingxiang__mobile__steeresponse__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEEResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__steeresponse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Dingxiang__Mobile__STEEResponse *
       com__dingxiang__mobile__steeresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Dingxiang__Mobile__STEEResponse *)
     protobuf_c_message_unpack (&com__dingxiang__mobile__steeresponse__descriptor,
                                allocator, len, data);
}
void   com__dingxiang__mobile__steeresponse__free_unpacked
                     (Com__Dingxiang__Mobile__STEEResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__dingxiang__mobile__steeresponse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   com__dingxiang__mobile__timestamp__init
                     (Com__Dingxiang__Mobile__Timestamp         *message)
{
  static const Com__Dingxiang__Mobile__Timestamp init_value = COM__DINGXIANG__MOBILE__TIMESTAMP__INIT;
  *message = init_value;
}
size_t com__dingxiang__mobile__timestamp__get_packed_size
                     (const Com__Dingxiang__Mobile__Timestamp *message)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__timestamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__dingxiang__mobile__timestamp__pack
                     (const Com__Dingxiang__Mobile__Timestamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__timestamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__dingxiang__mobile__timestamp__pack_to_buffer
                     (const Com__Dingxiang__Mobile__Timestamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__dingxiang__mobile__timestamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Dingxiang__Mobile__Timestamp *
       com__dingxiang__mobile__timestamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Dingxiang__Mobile__Timestamp *)
     protobuf_c_message_unpack (&com__dingxiang__mobile__timestamp__descriptor,
                                allocator, len, data);
}
void   com__dingxiang__mobile__timestamp__free_unpacked
                     (Com__Dingxiang__Mobile__Timestamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &com__dingxiang__mobile__timestamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
//static const ProtobufCEnumValue com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number[2] =
//{
//  { "Android", "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSTYPE__Android", 0 },
//  { "iOS", "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSTYPE__iOS", 1 },
//};

static ProtobufCEnumValue com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number[2];
void init_com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number() {
    com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number[0].name = "Android";
    com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number[0].c_name = "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSTYPE__Android";
    com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number[0].value = 0;
    com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number[1].name = "iOS";
    com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number[1].c_name = "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSTYPE__iOS";
    com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number[1].value = 1;
}

static const ProtobufCIntRange com__dingxiang__mobile__steerequest_header__ostype__value_ranges[] = {
       {0, 0},{0, 2}
};

// static const ProtobufCEnumValueIndex com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_name[2] =
// {
//   { "Android", 0 },
//   { "iOS", 1 },
// };

static ProtobufCEnumValueIndex com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_name[2];
void init_com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_name() {
    com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_name[0].name = "Android";
    com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_name[0].index = 0;
    com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_name[1].name = "iOS";
    com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_name[1].index = 1;
}

// const ProtobufCEnumDescriptor com__dingxiang__mobile__steerequest_header__ostype__descriptor =
// {
//   PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
//   "com.dingxiang.mobile.STEERequestHeader.OSType",
//   "OSType",
//   "Com__Dingxiang__Mobile__STEERequestHeader__OSType",
//   "com.dingxiang.mobile",
//   2,
//   com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number,
//   2,
//   com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_name,
//   1,
//   com__dingxiang__mobile__steerequest_header__ostype__value_ranges,
//   NULL,NULL,NULL,NULL   /* reserved[1234] */
// };

ProtobufCEnumDescriptor com__dingxiang__mobile__steerequest_header__ostype__descriptor;
void init_com__dingxiang__mobile__steerequest_header__ostype__descriptor() {
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.magic  = PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.name  = "com.dingxiang.mobile.STEERequestHeader.OSType";
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.short_name  = "OSType";
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.c_name  = "Com__Dingxiang__Mobile__STEERequestHeader__OSType";
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.package_name  = "com.dingxiang.mobile";
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.n_values  = 2;
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.values  = com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number;
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.n_value_names  = 2;
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.values_by_name  = com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_name;
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.n_value_ranges  = 1;
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.value_ranges  = com__dingxiang__mobile__steerequest_header__ostype__value_ranges;
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.reserved1  = NULL;
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.reserved2  = NULL;
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.reserved3  = NULL;
    com__dingxiang__mobile__steerequest_header__ostype__descriptor.reserved4  = NULL;
}

//static const ProtobufCEnumValue com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[4] =
//{
//  { "ARM", "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__ARM", 0 },
//  { "X86", "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__X86", 1 },
//  { "X86_64", "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__X86_64", 2 },
//  { "ARM64", "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__ARM64", 3 },
//};

static ProtobufCEnumValue com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[4];
void init_com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number() {
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[0].name = "ARM";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[0].c_name = "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__ARM";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[0].value = 0;
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[1].name = "X86";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[1].c_name = "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__X86";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[1].value = 1;
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[2].name = "X86_64";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[2].c_name = "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__X86_64";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[2].value = 2;
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[3].name = "ARM64";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[3].c_name = "COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__ARM64";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number[3].value = 3;
}

static const ProtobufCIntRange com__dingxiang__mobile__steerequest_header__osarch__value_ranges[] = {
{0, 0},{0, 4}
};

// static const ProtobufCEnumValueIndex com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name[4] =
// {
//   { "ARM", 0 },
//   { "ARM64", 3 },
//   { "X86", 1 },
//   { "X86_64", 2 },
// };

static ProtobufCEnumValueIndex com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name[4];
void init_com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name() {
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name[0].name = "ARM";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name[0].index = 0;
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name[1].name = "ARM64";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name[1].index = 3;
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name[2].name = "X86";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name[2].index = 1;
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name[3].name = "X86_64";
    com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name[3].index = 2;
}

// const ProtobufCEnumDescriptor com__dingxiang__mobile__steerequest_header__osarch__descriptor =
// {
//   PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
//   "com.dingxiang.mobile.STEERequestHeader.OSArch",
//   "OSArch",
//   "Com__Dingxiang__Mobile__STEERequestHeader__OSArch",
//   "com.dingxiang.mobile",
//   4,
//   com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number,
//   4,
//   com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name,
//   1,
//   com__dingxiang__mobile__steerequest_header__osarch__value_ranges,
//   NULL,NULL,NULL,NULL   /* reserved[1234] */
// };

ProtobufCEnumDescriptor com__dingxiang__mobile__steerequest_header__osarch__descriptor;
void init_com__dingxiang__mobile__steerequest_header__osarch__descriptor() {
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.magic  = PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.name  = "com.dingxiang.mobile.STEERequestHeader.OSArch";
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.short_name  = "OSArch";
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.c_name  = "Com__Dingxiang__Mobile__STEERequestHeader__OSArch";
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.n_values  = 4;
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.values  = com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number;
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.n_value_names = 4;
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.values_by_name = com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name;
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.n_value_ranges = 1;
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.value_ranges = com__dingxiang__mobile__steerequest_header__osarch__value_ranges;
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.reserved1  = NULL;
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.reserved2  = NULL;
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.reserved3  = NULL;
    com__dingxiang__mobile__steerequest_header__osarch__descriptor.reserved4  = NULL;
}


// static const ProtobufCFieldDescriptor com__dingxiang__mobile__steerequest_header__field_descriptors[10] =
// {
//   {
//     "sdk_ver",
//     1,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_STRING,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, sdk_ver),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "app_ver",
//     2,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_STRING,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, app_ver),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "app_ver_code",
//     3,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_INT32,
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, has_app_ver_code),
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, app_ver_code),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "app_key",
//     4,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_STRING,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, app_key),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "os_type",
//     5,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_ENUM,
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, has_os_type),
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, os_type),
//     &com__dingxiang__mobile__steerequest_header__ostype__descriptor,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "os_ver",
//     6,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_STRING,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, os_ver),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "const_id",
//     7,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_STRING,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, const_id),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "proto_version",
//     8,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_INT32,
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, has_proto_version),
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, proto_version),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "app_code",
//     9,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_STRING,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, app_code),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "os_arch",
//     10,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_ENUM,
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, has_os_arch),
//     offsetof(Com__Dingxiang__Mobile__STEERequestHeader, os_arch),
//     &com__dingxiang__mobile__steerequest_header__osarch__descriptor,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
// };

static ProtobufCFieldDescriptor com__dingxiang__mobile__steerequest_header__field_descriptors[10];
void init_com__dingxiang__mobile__steerequest_header__field_descriptors() {

    com__dingxiang__mobile__steerequest_header__field_descriptors[0].name = "sdk_ver";
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].id = 1;
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].type = PROTOBUF_C_TYPE_STRING;
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].quantifier_offset = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, sdk_ver);
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].descriptor = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].default_value = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].reserved_flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[0].reserved3 = NULL;

    com__dingxiang__mobile__steerequest_header__field_descriptors[1].name = "app_ver";
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].id = 2;
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].type = PROTOBUF_C_TYPE_STRING;
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].quantifier_offset = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, app_ver);
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].descriptor = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].default_value = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].reserved_flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[1].reserved3 = NULL;

    com__dingxiang__mobile__steerequest_header__field_descriptors[2].name = "app_ver_code";
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].id = 3;
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].type = PROTOBUF_C_TYPE_INT32;
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].quantifier_offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, has_app_ver_code);
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, app_ver_code);
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].descriptor = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].default_value = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].reserved_flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[2].reserved3 = NULL;

    com__dingxiang__mobile__steerequest_header__field_descriptors[3].name = "app_key";
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].id = 4;
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].type = PROTOBUF_C_TYPE_STRING;
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].quantifier_offset = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, app_key);
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].descriptor = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].default_value = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].reserved_flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[3].reserved3 = NULL;

    com__dingxiang__mobile__steerequest_header__field_descriptors[4].name = "os_type";
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].id = 5;
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].type = PROTOBUF_C_TYPE_ENUM;
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].quantifier_offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, has_os_type);
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, os_type);
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].descriptor = &com__dingxiang__mobile__steerequest_header__ostype__descriptor;
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].default_value = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].reserved_flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[4].reserved3 = NULL;

    com__dingxiang__mobile__steerequest_header__field_descriptors[5].name = "os_ver";
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].id = 6;
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].type = PROTOBUF_C_TYPE_STRING;
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].quantifier_offset = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, os_ver);
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].descriptor = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].default_value = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].reserved_flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[5].reserved3 = NULL;

    com__dingxiang__mobile__steerequest_header__field_descriptors[6].name = "const_id";
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].id = 7;
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].type = PROTOBUF_C_TYPE_STRING;
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].quantifier_offset = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, const_id);
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].descriptor = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].default_value = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].reserved_flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[6].reserved3 = NULL;

    com__dingxiang__mobile__steerequest_header__field_descriptors[7].name = "proto_version";
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].id = 8;
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].type = PROTOBUF_C_TYPE_INT32;
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].quantifier_offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, has_proto_version);
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, proto_version);
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].descriptor = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].default_value = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].reserved_flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[7].reserved3 = NULL;

    com__dingxiang__mobile__steerequest_header__field_descriptors[8].name = "app_code";
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].id = 9;
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].type = PROTOBUF_C_TYPE_STRING;
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].quantifier_offset = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, app_code);
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].descriptor = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].default_value = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].reserved_flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[8].reserved3 = NULL;

    com__dingxiang__mobile__steerequest_header__field_descriptors[9].name = "os_arch";
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].id = 10;
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].type = PROTOBUF_C_TYPE_ENUM;
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].quantifier_offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, has_os_arch);
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].offset = offsetof(Com__Dingxiang__Mobile__STEERequestHeader, os_arch);
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].descriptor = &com__dingxiang__mobile__steerequest_header__osarch__descriptor;
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].default_value = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].reserved_flags = 0;
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__field_descriptors[9].reserved3 = NULL;
}

static const unsigned com__dingxiang__mobile__steerequest_header__field_indices_by_name[] = {
  8,   /* field[8] = app_code */
  3,   /* field[3] = app_key */
  1,   /* field[1] = app_ver */
  2,   /* field[2] = app_ver_code */
  6,   /* field[6] = const_id */
  9,   /* field[9] = os_arch */
  4,   /* field[4] = os_type */
  5,   /* field[5] = os_ver */
  7,   /* field[7] = proto_version */
  0,   /* field[0] = sdk_ver */
};
static const ProtobufCIntRange com__dingxiang__mobile__steerequest_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
// const ProtobufCMessageDescriptor com__dingxiang__mobile__steerequest_header__descriptor =
// {
//   PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
//   "com.dingxiang.mobile.STEERequestHeader",
//   "STEERequestHeader",
//   "Com__Dingxiang__Mobile__STEERequestHeader",
//   "com.dingxiang.mobile",
//   sizeof(Com__Dingxiang__Mobile__STEERequestHeader),
//   10,
//   com__dingxiang__mobile__steerequest_header__field_descriptors,
//   com__dingxiang__mobile__steerequest_header__field_indices_by_name,
//   1,  com__dingxiang__mobile__steerequest_header__number_ranges,
//   (ProtobufCMessageInit) com__dingxiang__mobile__steerequest_header__init,
//   NULL,NULL,NULL    /* reserved[123] */
// };

ProtobufCMessageDescriptor com__dingxiang__mobile__steerequest_header__descriptor;
void init_com__dingxiang__mobile__steerequest_header__descriptor() {

    com__dingxiang__mobile__steerequest_header__descriptor.magic = PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steerequest_header__descriptor.name = "com.dingxiang.mobile.STEERequestHeader";
    com__dingxiang__mobile__steerequest_header__descriptor.short_name = "STEERequestHeader";
    com__dingxiang__mobile__steerequest_header__descriptor.c_name = "Com__Dingxiang__Mobile__STEERequestHeader";
    com__dingxiang__mobile__steerequest_header__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steerequest_header__descriptor.sizeof_message = sizeof(Com__Dingxiang__Mobile__STEERequestHeader);
    com__dingxiang__mobile__steerequest_header__descriptor.n_fields = 10;
    com__dingxiang__mobile__steerequest_header__descriptor.fields = com__dingxiang__mobile__steerequest_header__field_descriptors;
    com__dingxiang__mobile__steerequest_header__descriptor.fields_sorted_by_name = com__dingxiang__mobile__steerequest_header__field_indices_by_name;
    com__dingxiang__mobile__steerequest_header__descriptor.n_field_ranges = 1;
    com__dingxiang__mobile__steerequest_header__descriptor.field_ranges = com__dingxiang__mobile__steerequest_header__number_ranges;
    com__dingxiang__mobile__steerequest_header__descriptor.message_init = (ProtobufCMessageInit) com__dingxiang__mobile__steerequest_header__init;
    com__dingxiang__mobile__steerequest_header__descriptor.reserved1 = NULL;
    com__dingxiang__mobile__steerequest_header__descriptor.reserved2 = NULL;
    com__dingxiang__mobile__steerequest_header__descriptor.reserved3 = NULL;
}

// static const ProtobufCFieldDescriptor com__dingxiang__mobile__steerequest__field_descriptors[3] =
// {
//   {
//     "header",
//     1,
//     PROTOBUF_C_LABEL_REQUIRED,
//     PROTOBUF_C_TYPE_MESSAGE,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEERequest, header),
//     &com__dingxiang__mobile__steerequest_header__descriptor,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "type",
//     2,
//     PROTOBUF_C_LABEL_REQUIRED,
//     PROTOBUF_C_TYPE_ENUM,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEERequest, type),
//     &com__dingxiang__mobile__steedata_type__descriptor,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "data",
//     3,
//     PROTOBUF_C_LABEL_REQUIRED,
//     PROTOBUF_C_TYPE_BYTES,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEERequest, data),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
// };

static ProtobufCFieldDescriptor com__dingxiang__mobile__steerequest__field_descriptors[3];
void init_com__dingxiang__mobile__steerequest__field_descriptors() {

    com__dingxiang__mobile__steerequest__field_descriptors[0].name = "header";
    com__dingxiang__mobile__steerequest__field_descriptors[0].id = 1;
    com__dingxiang__mobile__steerequest__field_descriptors[0].label = PROTOBUF_C_LABEL_REQUIRED;
    com__dingxiang__mobile__steerequest__field_descriptors[0].type = PROTOBUF_C_TYPE_MESSAGE;
    com__dingxiang__mobile__steerequest__field_descriptors[0].quantifier_offset = 0;
    com__dingxiang__mobile__steerequest__field_descriptors[0].offset = offsetof(Com__Dingxiang__Mobile__STEERequest, header);
    com__dingxiang__mobile__steerequest__field_descriptors[0].descriptor = &com__dingxiang__mobile__steerequest_header__descriptor;
    com__dingxiang__mobile__steerequest__field_descriptors[0].default_value = NULL;
    com__dingxiang__mobile__steerequest__field_descriptors[0].flags = 0;
    com__dingxiang__mobile__steerequest__field_descriptors[0].reserved_flags = 0;
    com__dingxiang__mobile__steerequest__field_descriptors[0].reserved2 = NULL;
    com__dingxiang__mobile__steerequest__field_descriptors[0].reserved3 = NULL;

    com__dingxiang__mobile__steerequest__field_descriptors[1].name = "type";
    com__dingxiang__mobile__steerequest__field_descriptors[1].id = 2;
    com__dingxiang__mobile__steerequest__field_descriptors[1].label = PROTOBUF_C_LABEL_REQUIRED;
    com__dingxiang__mobile__steerequest__field_descriptors[1].type = PROTOBUF_C_TYPE_ENUM;
    com__dingxiang__mobile__steerequest__field_descriptors[1].quantifier_offset = 0;
    com__dingxiang__mobile__steerequest__field_descriptors[1].offset = offsetof(Com__Dingxiang__Mobile__STEERequest, type);
    com__dingxiang__mobile__steerequest__field_descriptors[1].descriptor = &com__dingxiang__mobile__steedata_type__descriptor;
    com__dingxiang__mobile__steerequest__field_descriptors[1].default_value = NULL;
    com__dingxiang__mobile__steerequest__field_descriptors[1].flags = 0;
    com__dingxiang__mobile__steerequest__field_descriptors[1].reserved_flags = 0;
    com__dingxiang__mobile__steerequest__field_descriptors[1].reserved2 = NULL;
    com__dingxiang__mobile__steerequest__field_descriptors[1].reserved3 = NULL;

    com__dingxiang__mobile__steerequest__field_descriptors[2].name = "data";
    com__dingxiang__mobile__steerequest__field_descriptors[2].id = 3;
    com__dingxiang__mobile__steerequest__field_descriptors[2].label = PROTOBUF_C_LABEL_REQUIRED;
    com__dingxiang__mobile__steerequest__field_descriptors[2].type = PROTOBUF_C_TYPE_BYTES;
    com__dingxiang__mobile__steerequest__field_descriptors[2].quantifier_offset = 0;
    com__dingxiang__mobile__steerequest__field_descriptors[2].offset = offsetof(Com__Dingxiang__Mobile__STEERequest, data);
    com__dingxiang__mobile__steerequest__field_descriptors[2].descriptor = NULL;
    com__dingxiang__mobile__steerequest__field_descriptors[2].default_value = NULL;
    com__dingxiang__mobile__steerequest__field_descriptors[2].flags = 0;
    com__dingxiang__mobile__steerequest__field_descriptors[2].reserved_flags = 0;
    com__dingxiang__mobile__steerequest__field_descriptors[2].reserved2 = NULL;
    com__dingxiang__mobile__steerequest__field_descriptors[2].reserved3 = NULL;
}

static const unsigned com__dingxiang__mobile__steerequest__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = header */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange com__dingxiang__mobile__steerequest__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};

// const ProtobufCMessageDescriptor com__dingxiang__mobile__steerequest__descriptor =
// {
//   PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
//   "com.dingxiang.mobile.STEERequest",
//   "STEERequest",
//   "Com__Dingxiang__Mobile__STEERequest",
//   "com.dingxiang.mobile",
//   sizeof(Com__Dingxiang__Mobile__STEERequest),
//   3,
//   com__dingxiang__mobile__steerequest__field_descriptors,
//   com__dingxiang__mobile__steerequest__field_indices_by_name,
//   1,  com__dingxiang__mobile__steerequest__number_ranges,
//   (ProtobufCMessageInit) com__dingxiang__mobile__steerequest__init,
//   NULL,NULL,NULL    /* reserved[123] */
// };

ProtobufCMessageDescriptor com__dingxiang__mobile__steerequest__descriptor;
void init_com__dingxiang__mobile__steerequest__descriptor() {
    com__dingxiang__mobile__steerequest__descriptor.magic = PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steerequest__descriptor.name = "com.dingxiang.mobile.STEERequest";
    com__dingxiang__mobile__steerequest__descriptor.short_name = "STEERequest";
    com__dingxiang__mobile__steerequest__descriptor.c_name = "Com__Dingxiang__Mobile__STEERequest";
    com__dingxiang__mobile__steerequest__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steerequest__descriptor.sizeof_message = sizeof(Com__Dingxiang__Mobile__STEERequest);
    com__dingxiang__mobile__steerequest__descriptor.n_fields = 3;
    com__dingxiang__mobile__steerequest__descriptor.fields = com__dingxiang__mobile__steerequest__field_descriptors;
    com__dingxiang__mobile__steerequest__descriptor.fields_sorted_by_name = com__dingxiang__mobile__steerequest__field_indices_by_name;
    com__dingxiang__mobile__steerequest__descriptor.n_field_ranges = 1;
    com__dingxiang__mobile__steerequest__descriptor.field_ranges = com__dingxiang__mobile__steerequest__number_ranges;
    com__dingxiang__mobile__steerequest__descriptor.message_init = (ProtobufCMessageInit) com__dingxiang__mobile__steerequest__init;
    com__dingxiang__mobile__steerequest__descriptor.reserved1 = NULL;
    com__dingxiang__mobile__steerequest__descriptor.reserved2 = NULL;
    com__dingxiang__mobile__steerequest__descriptor.reserved3 = NULL;
}

// static const ProtobufCFieldDescriptor com__dingxiang__mobile__steeresponse__field_descriptors[3] =
// {
//   {
//     "type",
//     1,
//     PROTOBUF_C_LABEL_REQUIRED,
//     PROTOBUF_C_TYPE_ENUM,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEEResponse, type),
//     &com__dingxiang__mobile__steedata_type__descriptor,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "data",
//     2,
//     PROTOBUF_C_LABEL_REQUIRED,
//     PROTOBUF_C_TYPE_BYTES,
//     0,    quantifier_offset 
//     offsetof(Com__Dingxiang__Mobile__STEEResponse, data),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "err_code",
//     3,
//     PROTOBUF_C_LABEL_REQUIRED,
//     PROTOBUF_C_TYPE_ENUM,
//     0,   /* quantifier_offset */
//     offsetof(Com__Dingxiang__Mobile__STEEResponse, err_code),
//     &com__dingxiang__mobile__steeerror_code__descriptor,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
// };
static ProtobufCFieldDescriptor com__dingxiang__mobile__steeresponse__field_descriptors[3];

void init_com__dingxiang__mobile__steeresponse__field_descriptors() {

    com__dingxiang__mobile__steeresponse__field_descriptors[0].name = "type";
    com__dingxiang__mobile__steeresponse__field_descriptors[0].id = 1;
    com__dingxiang__mobile__steeresponse__field_descriptors[0].label = PROTOBUF_C_LABEL_REQUIRED;
    com__dingxiang__mobile__steeresponse__field_descriptors[0].type = PROTOBUF_C_TYPE_ENUM;
    com__dingxiang__mobile__steeresponse__field_descriptors[0].quantifier_offset = 0;
    com__dingxiang__mobile__steeresponse__field_descriptors[0].offset = offsetof(Com__Dingxiang__Mobile__STEEResponse, type);
    com__dingxiang__mobile__steeresponse__field_descriptors[0].descriptor = &com__dingxiang__mobile__steedata_type__descriptor;
    com__dingxiang__mobile__steeresponse__field_descriptors[0].default_value = NULL;
    com__dingxiang__mobile__steeresponse__field_descriptors[0].flags = 0;
    com__dingxiang__mobile__steeresponse__field_descriptors[0].reserved_flags = 0;
    com__dingxiang__mobile__steeresponse__field_descriptors[0].reserved2 = NULL;
    com__dingxiang__mobile__steeresponse__field_descriptors[0].reserved3 = NULL;

    com__dingxiang__mobile__steeresponse__field_descriptors[1].name = "data";
    com__dingxiang__mobile__steeresponse__field_descriptors[1].id = 2;
    com__dingxiang__mobile__steeresponse__field_descriptors[1].label = PROTOBUF_C_LABEL_REQUIRED;
    com__dingxiang__mobile__steeresponse__field_descriptors[1].type = PROTOBUF_C_TYPE_BYTES;
    com__dingxiang__mobile__steeresponse__field_descriptors[1].quantifier_offset = 0;
    com__dingxiang__mobile__steeresponse__field_descriptors[1].offset = offsetof(Com__Dingxiang__Mobile__STEEResponse, data);
    com__dingxiang__mobile__steeresponse__field_descriptors[1].descriptor = NULL;
    com__dingxiang__mobile__steeresponse__field_descriptors[1].default_value = NULL;
    com__dingxiang__mobile__steeresponse__field_descriptors[1].flags = 0;
    com__dingxiang__mobile__steeresponse__field_descriptors[1].reserved_flags = 0;
    com__dingxiang__mobile__steeresponse__field_descriptors[1].reserved2 = NULL;
    com__dingxiang__mobile__steeresponse__field_descriptors[1].reserved3 = NULL;

    com__dingxiang__mobile__steeresponse__field_descriptors[2].name = "err_code";
    com__dingxiang__mobile__steeresponse__field_descriptors[2].id = 3;
    com__dingxiang__mobile__steeresponse__field_descriptors[2].label = PROTOBUF_C_LABEL_REQUIRED;
    com__dingxiang__mobile__steeresponse__field_descriptors[2].type = PROTOBUF_C_TYPE_ENUM;
    com__dingxiang__mobile__steeresponse__field_descriptors[2].quantifier_offset = 0;
    com__dingxiang__mobile__steeresponse__field_descriptors[2].offset = offsetof(Com__Dingxiang__Mobile__STEEResponse, err_code);
    com__dingxiang__mobile__steeresponse__field_descriptors[2].descriptor = &com__dingxiang__mobile__steeerror_code__descriptor;
    com__dingxiang__mobile__steeresponse__field_descriptors[2].default_value = NULL;
    com__dingxiang__mobile__steeresponse__field_descriptors[2].flags = 0;
    com__dingxiang__mobile__steeresponse__field_descriptors[2].reserved_flags = 0;
    com__dingxiang__mobile__steeresponse__field_descriptors[2].reserved2 = NULL;
    com__dingxiang__mobile__steeresponse__field_descriptors[2].reserved3 = NULL;
}


static const unsigned com__dingxiang__mobile__steeresponse__field_indices_by_name[] = {
  1,   /* field[1] = data */
  2,   /* field[2] = err_code */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange com__dingxiang__mobile__steeresponse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
// const ProtobufCMessageDescriptor com__dingxiang__mobile__steeresponse__descriptor =
// {
//   PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
//   "com.dingxiang.mobile.STEEResponse",
//   "STEEResponse",
//   "Com__Dingxiang__Mobile__STEEResponse",
//   "com.dingxiang.mobile",
//   sizeof(Com__Dingxiang__Mobile__STEEResponse),
//   3,
//   com__dingxiang__mobile__steeresponse__field_descriptors,
//   com__dingxiang__mobile__steeresponse__field_indices_by_name,
//   1,  com__dingxiang__mobile__steeresponse__number_ranges,
//   (ProtobufCMessageInit) com__dingxiang__mobile__steeresponse__init,
//   NULL,NULL,NULL    /* reserved[123] */
// };

ProtobufCMessageDescriptor com__dingxiang__mobile__steeresponse__descriptor;
void init_com__dingxiang__mobile__steeresponse__descriptor() {
    com__dingxiang__mobile__steeresponse__descriptor.magic = PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steeresponse__descriptor.name = "com.dingxiang.mobile.STEEResponse";
    com__dingxiang__mobile__steeresponse__descriptor.short_name = "STEEResponse";
    com__dingxiang__mobile__steeresponse__descriptor.c_name = "Com__Dingxiang__Mobile__STEEResponse";
    com__dingxiang__mobile__steeresponse__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steeresponse__descriptor.sizeof_message = sizeof(Com__Dingxiang__Mobile__STEEResponse);
    com__dingxiang__mobile__steeresponse__descriptor.n_fields = 3;
    com__dingxiang__mobile__steeresponse__descriptor.fields = com__dingxiang__mobile__steeresponse__field_descriptors;
    com__dingxiang__mobile__steeresponse__descriptor.fields_sorted_by_name = com__dingxiang__mobile__steeresponse__field_indices_by_name;
    com__dingxiang__mobile__steeresponse__descriptor.n_field_ranges = 1;
    com__dingxiang__mobile__steeresponse__descriptor.field_ranges = com__dingxiang__mobile__steeresponse__number_ranges;
    com__dingxiang__mobile__steeresponse__descriptor.message_init = (ProtobufCMessageInit) com__dingxiang__mobile__steeresponse__init;
    com__dingxiang__mobile__steeresponse__descriptor.reserved1 = NULL;
    com__dingxiang__mobile__steeresponse__descriptor.reserved2 = NULL;
    com__dingxiang__mobile__steeresponse__descriptor.reserved3 = NULL;
}

// static const ProtobufCFieldDescriptor com__dingxiang__mobile__timestamp__field_descriptors[2] =
// {
//   {
//     "seconds",
//     1,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_INT64,
//     offsetof(Com__Dingxiang__Mobile__Timestamp, has_seconds),
//     offsetof(Com__Dingxiang__Mobile__Timestamp, seconds),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
//   {
//     "nanos",
//     2,
//     PROTOBUF_C_LABEL_OPTIONAL,
//     PROTOBUF_C_TYPE_INT64,
//     offsetof(Com__Dingxiang__Mobile__Timestamp, has_nanos),
//     offsetof(Com__Dingxiang__Mobile__Timestamp, nanos),
//     NULL,
//     NULL,
//     0,             /* flags */
//     0,NULL,NULL    /* reserved1,reserved2, etc */
//   },
// };

static ProtobufCFieldDescriptor com__dingxiang__mobile__timestamp__field_descriptors[2];
void init_com__dingxiang__mobile__timestamp__field_descriptors() {

    com__dingxiang__mobile__timestamp__field_descriptors[0].name = "seconds";
    com__dingxiang__mobile__timestamp__field_descriptors[0].id = 1;
    com__dingxiang__mobile__timestamp__field_descriptors[0].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__timestamp__field_descriptors[0].type = PROTOBUF_C_TYPE_INT64;
    com__dingxiang__mobile__timestamp__field_descriptors[0].quantifier_offset = offsetof(Com__Dingxiang__Mobile__Timestamp, has_seconds);
    com__dingxiang__mobile__timestamp__field_descriptors[0].offset = offsetof(Com__Dingxiang__Mobile__Timestamp, seconds);
    com__dingxiang__mobile__timestamp__field_descriptors[0].descriptor = NULL;
    com__dingxiang__mobile__timestamp__field_descriptors[0].default_value = NULL;
    com__dingxiang__mobile__timestamp__field_descriptors[0].flags = 0;
    com__dingxiang__mobile__timestamp__field_descriptors[0].reserved_flags = 0;
    com__dingxiang__mobile__timestamp__field_descriptors[0].reserved2 = NULL;
    com__dingxiang__mobile__timestamp__field_descriptors[0].reserved3 = NULL;

    com__dingxiang__mobile__timestamp__field_descriptors[1].name = "nanos";
    com__dingxiang__mobile__timestamp__field_descriptors[1].id = 2;
    com__dingxiang__mobile__timestamp__field_descriptors[1].label = PROTOBUF_C_LABEL_OPTIONAL;
    com__dingxiang__mobile__timestamp__field_descriptors[1].type = PROTOBUF_C_TYPE_INT64;
    com__dingxiang__mobile__timestamp__field_descriptors[1].quantifier_offset = offsetof(Com__Dingxiang__Mobile__Timestamp, has_nanos);
    com__dingxiang__mobile__timestamp__field_descriptors[1].offset = offsetof(Com__Dingxiang__Mobile__Timestamp, nanos);
    com__dingxiang__mobile__timestamp__field_descriptors[1].descriptor = NULL;
    com__dingxiang__mobile__timestamp__field_descriptors[1].default_value = NULL;
    com__dingxiang__mobile__timestamp__field_descriptors[1].flags = 0;
    com__dingxiang__mobile__timestamp__field_descriptors[1].reserved_flags = 0;
    com__dingxiang__mobile__timestamp__field_descriptors[1].reserved2 = NULL;
    com__dingxiang__mobile__timestamp__field_descriptors[1].reserved3 = NULL;
}


static const unsigned com__dingxiang__mobile__timestamp__field_indices_by_name[] = {
  1,   /* field[1] = nanos */
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange com__dingxiang__mobile__timestamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
// const ProtobufCMessageDescriptor com__dingxiang__mobile__timestamp__descriptor =
// {
//   PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
//   "com.dingxiang.mobile.Timestamp",
//   "Timestamp",
//   "Com__Dingxiang__Mobile__Timestamp",
//   "com.dingxiang.mobile",
//   sizeof(Com__Dingxiang__Mobile__Timestamp),
//   2,
//   com__dingxiang__mobile__timestamp__field_descriptors,
//   com__dingxiang__mobile__timestamp__field_indices_by_name,
//   1,  com__dingxiang__mobile__timestamp__number_ranges,
//   (ProtobufCMessageInit) com__dingxiang__mobile__timestamp__init,
//   NULL,NULL,NULL    /* reserved[123] */
// };

ProtobufCMessageDescriptor com__dingxiang__mobile__timestamp__descriptor;
void init_com__dingxiang__mobile__timestamp__descriptor() {

    com__dingxiang__mobile__timestamp__descriptor.magic = PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__timestamp__descriptor.name = "com.dingxiang.mobile.Timestamp";
    com__dingxiang__mobile__timestamp__descriptor.short_name = "Timestamp";
    com__dingxiang__mobile__timestamp__descriptor.c_name = "Com__Dingxiang__Mobile__Timestamp";
    com__dingxiang__mobile__timestamp__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__timestamp__descriptor.sizeof_message = sizeof(Com__Dingxiang__Mobile__Timestamp);
    com__dingxiang__mobile__timestamp__descriptor.n_fields = 2;
    com__dingxiang__mobile__timestamp__descriptor.fields = com__dingxiang__mobile__timestamp__field_descriptors;
    com__dingxiang__mobile__timestamp__descriptor.fields_sorted_by_name = com__dingxiang__mobile__timestamp__field_indices_by_name;
    com__dingxiang__mobile__timestamp__descriptor.n_field_ranges = 1;
    com__dingxiang__mobile__timestamp__descriptor.field_ranges = com__dingxiang__mobile__timestamp__number_ranges;
    com__dingxiang__mobile__timestamp__descriptor.message_init = (ProtobufCMessageInit) com__dingxiang__mobile__timestamp__init;
    com__dingxiang__mobile__timestamp__descriptor.reserved1 = NULL;
    com__dingxiang__mobile__timestamp__descriptor.reserved2 = NULL;
    com__dingxiang__mobile__timestamp__descriptor.reserved3 = NULL;
}

// static const ProtobufCEnumValue com__dingxiang__mobile__steedata_type__enum_values_by_number[4] =
// {
//   { "DATATYPE_GET_REPORT_CONFIG", "COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_GET_REPORT_CONFIG", 1001 },
//   { "DATATYPE_DO_REPORT_DATA", "COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_DO_REPORT_DATA", 1002 },
//   { "DATATYPE_CHECK_REQ", "COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_CHECK_REQ", 1003 },
//   { "DATATYPE_EVENT_REPORT", "COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_EVENT_REPORT", 1004 },
// };

static ProtobufCEnumValue com__dingxiang__mobile__steedata_type__enum_values_by_number[4];
void init_com__dingxiang__mobile__steedata_type__enum_values_by_number() {
    com__dingxiang__mobile__steedata_type__enum_values_by_number[0].name = "DATATYPE_GET_REPORT_CONFIG";
    com__dingxiang__mobile__steedata_type__enum_values_by_number[0].c_name = "COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_GET_REPORT_CONFIG";
    com__dingxiang__mobile__steedata_type__enum_values_by_number[0].value = 1001;
    com__dingxiang__mobile__steedata_type__enum_values_by_number[1].name = "DATATYPE_DO_REPORT_DATA";
    com__dingxiang__mobile__steedata_type__enum_values_by_number[1].c_name = "COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_DO_REPORT_DATA";
    com__dingxiang__mobile__steedata_type__enum_values_by_number[1].value = 1002;
    com__dingxiang__mobile__steedata_type__enum_values_by_number[2].name = "DATATYPE_CHECK_REQ";
    com__dingxiang__mobile__steedata_type__enum_values_by_number[2].c_name = "COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_CHECK_REQ";
    com__dingxiang__mobile__steedata_type__enum_values_by_number[2].value = 1003;
    com__dingxiang__mobile__steedata_type__enum_values_by_number[3].name = "DATATYPE_EVENT_REPORT";
    com__dingxiang__mobile__steedata_type__enum_values_by_number[3].c_name = "COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_EVENT_REPORT";
    com__dingxiang__mobile__steedata_type__enum_values_by_number[3].value = 1004;
}

static const ProtobufCIntRange com__dingxiang__mobile__steedata_type__value_ranges[] = {
{1001, 0},{0, 4}
};
// static const ProtobufCEnumValueIndex com__dingxiang__mobile__steedata_type__enum_values_by_name[4] =
// {
//   { "DATATYPE_CHECK_REQ", 2 },
//   { "DATATYPE_DO_REPORT_DATA", 1 },
//   { "DATATYPE_EVENT_REPORT", 3 },
//   { "DATATYPE_GET_REPORT_CONFIG", 0 },
// };

static ProtobufCEnumValueIndex com__dingxiang__mobile__steedata_type__enum_values_by_name[4];
void init_com__dingxiang__mobile__steedata_type__enum_values_by_name() {
    com__dingxiang__mobile__steedata_type__enum_values_by_name[0].name = "DATATYPE_CHECK_REQ";
    com__dingxiang__mobile__steedata_type__enum_values_by_name[0].index = 2;
    com__dingxiang__mobile__steedata_type__enum_values_by_name[1].name = "DATATYPE_DO_REPORT_DATA";
    com__dingxiang__mobile__steedata_type__enum_values_by_name[1].index = 1;
    com__dingxiang__mobile__steedata_type__enum_values_by_name[2].name = "DATATYPE_EVENT_REPORT";
    com__dingxiang__mobile__steedata_type__enum_values_by_name[2].index = 3;
    com__dingxiang__mobile__steedata_type__enum_values_by_name[3].name = "DATATYPE_GET_REPORT_CONFIG";
    com__dingxiang__mobile__steedata_type__enum_values_by_name[3].index = 0;
}


// const ProtobufCEnumDescriptor com__dingxiang__mobile__steedata_type__descriptor =
// {
//   PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
//   "com.dingxiang.mobile.STEEDataType",
//   "STEEDataType",
//   "Com__Dingxiang__Mobile__STEEDataType",
//   "com.dingxiang.mobile",
//   4,
//   com__dingxiang__mobile__steedata_type__enum_values_by_number,
//   4,
//   com__dingxiang__mobile__steedata_type__enum_values_by_name,
//   1,
//   com__dingxiang__mobile__steedata_type__value_ranges,
//   NULL,NULL,NULL,NULL   /* reserved[1234] */
// };

ProtobufCEnumDescriptor com__dingxiang__mobile__steedata_type__descriptor;
void init_com__dingxiang__mobile__steedata_type__descriptor() {
    com__dingxiang__mobile__steedata_type__descriptor.magic  = PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steedata_type__descriptor.name  = "com.dingxiang.mobile.STEEDataType";
    com__dingxiang__mobile__steedata_type__descriptor.short_name  = "STEEDataType";
    com__dingxiang__mobile__steedata_type__descriptor.c_name  = "Com__Dingxiang__Mobile__STEEDataType";
    com__dingxiang__mobile__steedata_type__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steedata_type__descriptor.n_values  = 4;
    com__dingxiang__mobile__steedata_type__descriptor.values  = com__dingxiang__mobile__steedata_type__enum_values_by_number;
    com__dingxiang__mobile__steedata_type__descriptor.n_value_names = 4;
    com__dingxiang__mobile__steedata_type__descriptor.values_by_name = com__dingxiang__mobile__steedata_type__enum_values_by_name;
    com__dingxiang__mobile__steedata_type__descriptor.n_value_ranges = 1;
    com__dingxiang__mobile__steedata_type__descriptor.value_ranges = com__dingxiang__mobile__steedata_type__value_ranges;
    com__dingxiang__mobile__steedata_type__descriptor.reserved1  = NULL;
    com__dingxiang__mobile__steedata_type__descriptor.reserved2  = NULL;
    com__dingxiang__mobile__steedata_type__descriptor.reserved3  = NULL;
    com__dingxiang__mobile__steedata_type__descriptor.reserved4  = NULL;
}


// static const ProtobufCEnumValue com__dingxiang__mobile__steeerror_code__enum_values_by_number[7] =
// {
//   { "ERR_RESOURE_LIMITE", "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_RESOURE_LIMITE", -10006 },
//   { "ERR_INTERNAL_SERVER_ERROR", "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_INTERNAL_SERVER_ERROR", -10005 },
//   { "ERR_DESERIALIZATION_FAILED", "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_DESERIALIZATION_FAILED", -10004 },
//   { "ERR_UNKONW_BUSINESS_TYPE", "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_UNKONW_BUSINESS_TYPE", -10003 },
//   { "ERR_CHECK_SIGN_FAILED", "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_CHECK_SIGN_FAILED", -10002 },
//   { "ERR_APP_KEY_NOT_FOUND_OR_NOT_EXISTS", "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_APP_KEY_NOT_FOUND_OR_NOT_EXISTS", -10001 },
//   { "ERR_NOERROR", "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_NOERROR", 0 },
// };

static ProtobufCEnumValue com__dingxiang__mobile__steeerror_code__enum_values_by_number[7];
void init_com__dingxiang__mobile__steeerror_code__enum_values_by_number() {
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[0].name = "ERR_RESOURE_LIMITE";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[0].c_name = "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_RESOURE_LIMITE";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[0].value = -10006;
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[1].name = "ERR_INTERNAL_SERVER_ERROR";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[1].c_name = "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_INTERNAL_SERVER_ERROR";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[1].value = -10005;
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[2].name = "ERR_DESERIALIZATION_FAILED";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[2].c_name = "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_DESERIALIZATION_FAILED";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[2].value = -10004;
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[3].name = "ERR_UNKONW_BUSINESS_TYPE";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[3].c_name = "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_UNKONW_BUSINESS_TYPE";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[3].value =  -10003;
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[4].name = "ERR_CHECK_SIGN_FAILED";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[4].c_name = "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_CHECK_SIGN_FAILED";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[4].value = -10002;
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[5].name = "ERR_APP_KEY_NOT_FOUND_OR_NOT_EXISTS";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[5].c_name = "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_APP_KEY_NOT_FOUND_OR_NOT_EXISTS";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[5].value = -10001;
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[6].name = "ERR_NOERROR";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[6].c_name = "COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_NOERROR";
    com__dingxiang__mobile__steeerror_code__enum_values_by_number[6].value = 0;
}


static const ProtobufCIntRange com__dingxiang__mobile__steeerror_code__value_ranges[] = {
{-10006, 0},{0, 6},{0, 7}
};
// static const ProtobufCEnumValueIndex com__dingxiang__mobile__steeerror_code__enum_values_by_name[7] =
// {
//   { "ERR_APP_KEY_NOT_FOUND_OR_NOT_EXISTS", 5 },
//   { "ERR_CHECK_SIGN_FAILED", 4 },
//   { "ERR_DESERIALIZATION_FAILED", 2 },
//   { "ERR_INTERNAL_SERVER_ERROR", 1 },
//   { "ERR_NOERROR", 6 },
//   { "ERR_RESOURE_LIMITE", 0 },
//   { "ERR_UNKONW_BUSINESS_TYPE", 3 },
// };

static ProtobufCEnumValueIndex com__dingxiang__mobile__steeerror_code__enum_values_by_name[7];
void init_com__dingxiang__mobile__steeerror_code__enum_values_by_name() {
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[0].name = "ERR_APP_KEY_NOT_FOUND_OR_NOT_EXISTS";
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[0].index = 5;
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[1].name = "ERR_CHECK_SIGN_FAILED";
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[1].index = 4;
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[2].name = "ERR_DESERIALIZATION_FAILED";
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[2].index = 2;
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[3].name = "ERR_INTERNAL_SERVER_ERROR";
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[3].index = 1;
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[4].name = "ERR_NOERROR";
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[4].index = 6;
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[5].name = "ERR_RESOURE_LIMITE";
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[5].index = 0;
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[6].name = "ERR_UNKONW_BUSINESS_TYPE";
    com__dingxiang__mobile__steeerror_code__enum_values_by_name[6].index = 3;
}

// const ProtobufCEnumDescriptor com__dingxiang__mobile__steeerror_code__descriptor =
// {
//   PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
//   "com.dingxiang.mobile.STEEErrorCode",
//   "STEEErrorCode",
//   "Com__Dingxiang__Mobile__STEEErrorCode",
//   "com.dingxiang.mobile",
//   7,
//   com__dingxiang__mobile__steeerror_code__enum_values_by_number,
//   7,
//   com__dingxiang__mobile__steeerror_code__enum_values_by_name,
//   2,
//   com__dingxiang__mobile__steeerror_code__value_ranges,
//   NULL,NULL,NULL,NULL   /* reserved[1234] */
// };

ProtobufCEnumDescriptor com__dingxiang__mobile__steeerror_code__descriptor;
void init_com__dingxiang__mobile__steeerror_code__descriptor() {
    com__dingxiang__mobile__steeerror_code__descriptor.magic  = PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC;
    com__dingxiang__mobile__steeerror_code__descriptor.name  = "com.dingxiang.mobile.STEEErrorCode";
    com__dingxiang__mobile__steeerror_code__descriptor.short_name  = "STEEErrorCode";
    com__dingxiang__mobile__steeerror_code__descriptor.c_name  = "Com__Dingxiang__Mobile__STEEErrorCode";
    com__dingxiang__mobile__steeerror_code__descriptor.package_name = "com.dingxiang.mobile";
    com__dingxiang__mobile__steeerror_code__descriptor.n_values  = 7;
    com__dingxiang__mobile__steeerror_code__descriptor.values  = com__dingxiang__mobile__steeerror_code__enum_values_by_number;
    com__dingxiang__mobile__steeerror_code__descriptor.n_value_names = 7;
    com__dingxiang__mobile__steeerror_code__descriptor.values_by_name = com__dingxiang__mobile__steeerror_code__enum_values_by_name;
    com__dingxiang__mobile__steeerror_code__descriptor.n_value_ranges = 1;
    com__dingxiang__mobile__steeerror_code__descriptor.value_ranges = com__dingxiang__mobile__steeerror_code__value_ranges;
    com__dingxiang__mobile__steeerror_code__descriptor.reserved1  = NULL;
    com__dingxiang__mobile__steeerror_code__descriptor.reserved2  = NULL;
    com__dingxiang__mobile__steeerror_code__descriptor.reserved3  = NULL;
    com__dingxiang__mobile__steeerror_code__descriptor.reserved4  = NULL;
}


void pb_stee_base_com__dingxiang__mobile__init() {

    init_com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_number();
    init_com__dingxiang__mobile__steerequest_header__ostype__enum_values_by_name();
    init_com__dingxiang__mobile__steerequest_header__ostype__descriptor();
    init_com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_number();
    init_com__dingxiang__mobile__steerequest_header__osarch__enum_values_by_name();
    init_com__dingxiang__mobile__steerequest_header__osarch__descriptor();
    init_com__dingxiang__mobile__steerequest_header__field_descriptors();
    init_com__dingxiang__mobile__steerequest_header__descriptor();
    init_com__dingxiang__mobile__steerequest__field_descriptors();
    init_com__dingxiang__mobile__steerequest__descriptor();
    init_com__dingxiang__mobile__steeresponse__field_descriptors();
    init_com__dingxiang__mobile__steeresponse__descriptor();
    init_com__dingxiang__mobile__timestamp__field_descriptors();
    init_com__dingxiang__mobile__timestamp__descriptor();
    init_com__dingxiang__mobile__steedata_type__enum_values_by_number();
    init_com__dingxiang__mobile__steedata_type__enum_values_by_name();
    init_com__dingxiang__mobile__steedata_type__descriptor();
    init_com__dingxiang__mobile__steeerror_code__enum_values_by_number();
    init_com__dingxiang__mobile__steeerror_code__enum_values_by_name();
    init_com__dingxiang__mobile__steeerror_code__descriptor();

};
