/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stee_base.proto */

#ifndef PROTOBUF_C_stee_5fbase_2eproto__INCLUDED
#define PROTOBUF_C_stee_5fbase_2eproto__INCLUDED

#include <protobuf-c/dx_protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

void pb_stee_base_com__dingxiang__mobile__init();


typedef struct _Com__Dingxiang__Mobile__STEERequestHeader Com__Dingxiang__Mobile__STEERequestHeader;
typedef struct _Com__Dingxiang__Mobile__STEERequest Com__Dingxiang__Mobile__STEERequest;
typedef struct _Com__Dingxiang__Mobile__STEEResponse Com__Dingxiang__Mobile__STEEResponse;
typedef struct _Com__Dingxiang__Mobile__Timestamp Com__Dingxiang__Mobile__Timestamp;


/* --- enums --- */

typedef enum _Com__Dingxiang__Mobile__STEERequestHeader__OSType {
  COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSTYPE__Android = 0,
  COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSTYPE__iOS = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSTYPE)
} Com__Dingxiang__Mobile__STEERequestHeader__OSType;
typedef enum _Com__Dingxiang__Mobile__STEERequestHeader__OSArch {
  COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__ARM = 0,
  COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__X86 = 1,
  COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__X86_64 = 2,
  COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__ARM64 = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH)
} Com__Dingxiang__Mobile__STEERequestHeader__OSArch;
typedef enum _Com__Dingxiang__Mobile__STEEDataType {
  /*
   *获取数据上传的策略配置
   */
  COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_GET_REPORT_CONFIG = 1001,
  /*
   *上报数据
   */
  COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_DO_REPORT_DATA = 1002,
  /*
   *风险上报和解释模块下发
   */
  COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_CHECK_REQ = 1003,
  /*
   *事件上报
   */
  COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_EVENT_REPORT = 1004
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COM__DINGXIANG__MOBILE__STEEDATA_TYPE)
} Com__Dingxiang__Mobile__STEEDataType;
/*
 * 通讯错误类型，服务器侧示情况添加
 */
typedef enum _Com__Dingxiang__Mobile__STEEErrorCode {
  /*
   * appKey不存在或者已经过期
   */
  COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_APP_KEY_NOT_FOUND_OR_NOT_EXISTS = -10001,
  /*
   * 验证签名失败
   */
  COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_CHECK_SIGN_FAILED = -10002,
  /*
   * 错误的业务类型
   */
  COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_UNKONW_BUSINESS_TYPE = -10003,
  /*
   * 反序列化失败
   */
  COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_DESERIALIZATION_FAILED = -10004,
  /*
   * 服务器内部异常
   */
  COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_INTERNAL_SERVER_ERROR = -10005,
  /*
   * 服务器限流
   */
  COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_RESOURE_LIMITE = -10006,
  COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_NOERROR = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COM__DINGXIANG__MOBILE__STEEERROR_CODE)
} Com__Dingxiang__Mobile__STEEErrorCode;

/* --- messages --- */

struct  _Com__Dingxiang__Mobile__STEERequestHeader
{
  ProtobufCMessage base;
  char *sdk_ver;
  char *app_ver;
  protobuf_c_boolean has_app_ver_code;
  int32_t app_ver_code;
  char *app_key;
  protobuf_c_boolean has_os_type;
  Com__Dingxiang__Mobile__STEERequestHeader__OSType os_type;
  char *os_ver;
  char *const_id;
  protobuf_c_boolean has_proto_version;
  int32_t proto_version;
  char *app_code;
  protobuf_c_boolean has_os_arch;
  Com__Dingxiang__Mobile__STEERequestHeader__OSArch os_arch;
};
#define COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__dingxiang__mobile__steerequest_header__descriptor) \
    , NULL, NULL, 0, 0, NULL, 0, COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSTYPE__Android, NULL, NULL, 0, 0, NULL, 0, COM__DINGXIANG__MOBILE__STEEREQUEST_HEADER__OSARCH__ARM }


struct  _Com__Dingxiang__Mobile__STEERequest
{
  ProtobufCMessage base;
  Com__Dingxiang__Mobile__STEERequestHeader *header;
  /*
   *业务类型
   */
  Com__Dingxiang__Mobile__STEEDataType type;
  /*
   *业务数据
   */
  ProtobufCBinaryData data;
};
#define COM__DINGXIANG__MOBILE__STEEREQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__dingxiang__mobile__steerequest__descriptor) \
    , NULL, COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_GET_REPORT_CONFIG, {0,NULL} }


struct  _Com__Dingxiang__Mobile__STEEResponse
{
  ProtobufCMessage base;
  Com__Dingxiang__Mobile__STEEDataType type;
  ProtobufCBinaryData data;
  /*
   *错误编码
   */
  Com__Dingxiang__Mobile__STEEErrorCode err_code;
};
#define COM__DINGXIANG__MOBILE__STEERESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__dingxiang__mobile__steeresponse__descriptor) \
    , COM__DINGXIANG__MOBILE__STEEDATA_TYPE__DATATYPE_GET_REPORT_CONFIG, {0,NULL}, COM__DINGXIANG__MOBILE__STEEERROR_CODE__ERR_APP_KEY_NOT_FOUND_OR_NOT_EXISTS }


struct  _Com__Dingxiang__Mobile__Timestamp
{
  ProtobufCMessage base;
  protobuf_c_boolean has_seconds;
  int64_t seconds;
  protobuf_c_boolean has_nanos;
  int64_t nanos;
};
#define COM__DINGXIANG__MOBILE__TIMESTAMP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__dingxiang__mobile__timestamp__descriptor) \
    , 0, 0, 0, 0 }


/* Com__Dingxiang__Mobile__STEERequestHeader methods */
void   com__dingxiang__mobile__steerequest_header__init
                     (Com__Dingxiang__Mobile__STEERequestHeader         *message);
size_t com__dingxiang__mobile__steerequest_header__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERequestHeader   *message);
size_t com__dingxiang__mobile__steerequest_header__pack
                     (const Com__Dingxiang__Mobile__STEERequestHeader   *message,
                      uint8_t             *out);
size_t com__dingxiang__mobile__steerequest_header__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERequestHeader   *message,
                      ProtobufCBuffer     *buffer);
Com__Dingxiang__Mobile__STEERequestHeader *
       com__dingxiang__mobile__steerequest_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__dingxiang__mobile__steerequest_header__free_unpacked
                     (Com__Dingxiang__Mobile__STEERequestHeader *message,
                      ProtobufCAllocator *allocator);
/* Com__Dingxiang__Mobile__STEERequest methods */
void   com__dingxiang__mobile__steerequest__init
                     (Com__Dingxiang__Mobile__STEERequest         *message);
size_t com__dingxiang__mobile__steerequest__get_packed_size
                     (const Com__Dingxiang__Mobile__STEERequest   *message);
size_t com__dingxiang__mobile__steerequest__pack
                     (const Com__Dingxiang__Mobile__STEERequest   *message,
                      uint8_t             *out);
size_t com__dingxiang__mobile__steerequest__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEERequest   *message,
                      ProtobufCBuffer     *buffer);
Com__Dingxiang__Mobile__STEERequest *
       com__dingxiang__mobile__steerequest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__dingxiang__mobile__steerequest__free_unpacked
                     (Com__Dingxiang__Mobile__STEERequest *message,
                      ProtobufCAllocator *allocator);
/* Com__Dingxiang__Mobile__STEEResponse methods */
void   com__dingxiang__mobile__steeresponse__init
                     (Com__Dingxiang__Mobile__STEEResponse         *message);
size_t com__dingxiang__mobile__steeresponse__get_packed_size
                     (const Com__Dingxiang__Mobile__STEEResponse   *message);
size_t com__dingxiang__mobile__steeresponse__pack
                     (const Com__Dingxiang__Mobile__STEEResponse   *message,
                      uint8_t             *out);
size_t com__dingxiang__mobile__steeresponse__pack_to_buffer
                     (const Com__Dingxiang__Mobile__STEEResponse   *message,
                      ProtobufCBuffer     *buffer);
Com__Dingxiang__Mobile__STEEResponse *
       com__dingxiang__mobile__steeresponse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__dingxiang__mobile__steeresponse__free_unpacked
                     (Com__Dingxiang__Mobile__STEEResponse *message,
                      ProtobufCAllocator *allocator);
/* Com__Dingxiang__Mobile__Timestamp methods */
void   com__dingxiang__mobile__timestamp__init
                     (Com__Dingxiang__Mobile__Timestamp         *message);
size_t com__dingxiang__mobile__timestamp__get_packed_size
                     (const Com__Dingxiang__Mobile__Timestamp   *message);
size_t com__dingxiang__mobile__timestamp__pack
                     (const Com__Dingxiang__Mobile__Timestamp   *message,
                      uint8_t             *out);
size_t com__dingxiang__mobile__timestamp__pack_to_buffer
                     (const Com__Dingxiang__Mobile__Timestamp   *message,
                      ProtobufCBuffer     *buffer);
Com__Dingxiang__Mobile__Timestamp *
       com__dingxiang__mobile__timestamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__dingxiang__mobile__timestamp__free_unpacked
                     (Com__Dingxiang__Mobile__Timestamp *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Dingxiang__Mobile__STEERequestHeader_Closure)
                 (const Com__Dingxiang__Mobile__STEERequestHeader *message,
                  void *closure_data);
typedef void (*Com__Dingxiang__Mobile__STEERequest_Closure)
                 (const Com__Dingxiang__Mobile__STEERequest *message,
                  void *closure_data);
typedef void (*Com__Dingxiang__Mobile__STEEResponse_Closure)
                 (const Com__Dingxiang__Mobile__STEEResponse *message,
                  void *closure_data);
typedef void (*Com__Dingxiang__Mobile__Timestamp_Closure)
                 (const Com__Dingxiang__Mobile__Timestamp *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern ProtobufCEnumDescriptor    com__dingxiang__mobile__steedata_type__descriptor;
extern ProtobufCEnumDescriptor    com__dingxiang__mobile__steeerror_code__descriptor;
extern ProtobufCMessageDescriptor com__dingxiang__mobile__steerequest_header__descriptor;
extern ProtobufCEnumDescriptor    com__dingxiang__mobile__steerequest_header__ostype__descriptor;
extern ProtobufCEnumDescriptor    com__dingxiang__mobile__steerequest_header__osarch__descriptor;
extern ProtobufCMessageDescriptor com__dingxiang__mobile__steerequest__descriptor;
extern ProtobufCMessageDescriptor com__dingxiang__mobile__steeresponse__descriptor;
extern ProtobufCMessageDescriptor com__dingxiang__mobile__timestamp__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_stee_5fbase_2eproto__INCLUDED */
