funcs:
  _ZGVZNSt:                           [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZNKSt:                             [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZNSt:                              [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZSt18make_exception_ptrINSt:       [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTCNSt:                            [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTINSt:                            [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTSNSt:                            [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTTNSt:                            [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTVNSt:                            [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZThn8_NKSt:                        [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZThn8_NSt:                         [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTv0_n12_NSt:                      [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZZNSt:                             [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZSt:                               [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTSSt:                             [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTVSt:                             [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZGVZNSt:                           [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTCNSt:                            [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTTNSt:                            [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZTv0:                              [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZThn8:                             [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZStpl:                             [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZN13securitystack:                 [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZNSs:                              [no-stee, no-bcf, no-fla, no-sub, no-spli]
  _ZN6google:                         [no-stee, no-bcf, no-fla, no-sub, no-spli]
 