//
// Created by blue on 2018/7/16.
//

#ifndef ANTI_AS_PROJECT_ANTI_CRASH_LOG_PREFIX_H
#define ANTI_AS_PROJECT_ANTI_CRASH_LOG_PREFIX_H

#define ANTI_CRASH_RANDOM                   99999

#define ANTI_DEBUG_ERR_BASE                 10000000
#define ANTI_DEBUG_ERR_PTRACE1              ANTI_DEBUG_ERR_BASE + 1000000
#define ANTI_DEBUG_ERR_PTRACE2              ANTI_DEBUG_ERR_BASE + 2000000
#define ANTI_DEBUG_ERR_DBG_ACTIVE           ANTI_DEBUG_ERR_BASE + 3000000
#define ANTI_DEBUG_ERR_PIPE_DIS             ANTI_DEBUG_ERR_BASE + 4000000 // 废弃
#define ANTI_DEBUG_ERR_RAP_SIG              ANTI_DEBUG_ERR_BASE + 5000000
#define ANTI_DEBUG_ERR_INNER                ANTI_DEBUG_ERR_BASE + 6000000
#define ANTI_DEBUG_ERR_PIPE_PARENT_DIS      ANTI_DEBUG_ERR_BASE + 7000000
#define ANTI_DEBUG_ERR_PIPE_SON_DIS         ANTI_DEBUG_ERR_BASE + 8000000
#define ANTI_DEBUG_ERR_HOOK                 ANTI_DEBUG_ERR_BASE + 9000000
#define ANTI_DEBUG_ERR_HOOK_JNI             ANTI_DEBUG_ERR_BASE + 9500000

#define ANTI_EMULATOR_ERR_BASE              20000000

#define ANTI_FLAW_JANUS_ERR_BASE            30000000

#define ANTI_INJECT_ERR_BASE                40000000
#define ANTI_INJECT_ERR_LIBS                ANTI_INJECT_ERR_BASE + 1000000
#define ANTI_INJECT_ERR_JARS                ANTI_INJECT_ERR_BASE + 2000000

#define ANTI_MEMDUMP_ERR_BASE               50000000

#define ANTI_MULTIRUN_ERR_BASE              60000000
#define ANTI_MULTIRUN_ERR_PKGS              ANTI_MULTIRUN_ERR_BASE + 1000000
#define ANTI_MULTIRUN_ERR_SOCKET            ANTI_MULTIRUN_ERR_BASE + 2000000
#define ANTI_MULTIRUN_ERR_XIAOMI_MULTI      ANTI_MULTIRUN_ERR_BASE + 3000000
#define ANTI_MULTIRUN_ERR_XIAOMI_SYSTEM     ANTI_MULTIRUN_ERR_BASE + 4000000

#define ANTI_ROOT_ERR_BASE                  70000000
#define ANTI_ROOT_ERR_BY_APK                ANTI_ROOT_ERR_BASE + 1000000
#define ANTI_ROOT_ERR_BY_PROPS              ANTI_ROOT_ERR_BASE + 2000000
#define ANTI_ROOT_ERR_BY_SU                 ANTI_ROOT_ERR_BASE + 3000000
#define ANTI_ROOT_ERR_BY_WHICH              ANTI_ROOT_ERR_BASE + 4000000

#define ANTI_VIRTUAL_APP_ERR_BASE           80000000
#define ANTI_VIRTUAL_APP_ERR_BY_JAVA        ANTI_VIRTUAL_APP_ERR_BASE + 1000000
#define ANTI_VIRTUAL_APP_ERR_BY_PKG         ANTI_VIRTUAL_APP_ERR_BASE + 2000000
#define ANTI_VIRTUAL_APP_ERR_BY_SO          ANTI_VIRTUAL_APP_ERR_BASE + 3000000


#endif //ANTI_AS_PROJECT_ANTI_CRASH_LOG_PREFIX_H
