#ifndef _FAILURE_CAUSE_H
#define _FAILURE_CAUSE_H

enum FAILURE_CAUSE {
    CAUSE_UNKNOWN, CAUSE_OUT_OF_DATE, CAUSE_DEVICE_NOT_PERMITTED, CAUSE_SUSPICIOUS_RUNTIME, CAUSE_PRODUCT_NAME_NOT_FOUND, CAUSE_MAX_LIMIT
};

#endif